import matplotlib.pyplot as plt
def plot(x, u, l, t):
    fig1, axs1 = plt.subplots(5,1)
    # plot configurations
    axs1[0].set_title('Configuration Trajectory')
    axs1[0].plot(t, x[0,:], linewidth=1.5)
    axs1[0].set_ylabel('Base_x')
    axs1[1].plot(t, x[1,:], linewidth=1.5)
    axs1[1].set_ylabel('Base_y')
    axs1[2].plot(t, x[2,:], linewidth=1.5)
    axs1[2].set_ylabel('Angle_1')
    axs1[3].plot(t, x[3,:], linewidth=1.5)
    axs1[3].set_ylabel('Angle_2')
    axs1[4].plot(t, x[4,:], linewidth=1.5)
    axs1[4].set_ylabel('Angle_3')
    axs1[2].set_xlabel('Time (s)')

    # plot controls
    fig2, axs2 = plt.subplots(3,1)
    axs2[0].set_title('Control Trajectory')
    axs2[0].plot(t, u[0,:], linewidth=1.5)
    axs2[0].set_ylabel('Joint 1')
    axs2[1].plot(t, u[1,:], linewidth=1.5)
    axs2[1].set_ylabel('Joint 2')
    axs2[2].plot(t, u[2,:], linewidth=1.5)
    axs2[2].set_ylabel('Joint 3')
    axs2[2].set_xlabel('Time (s)')

    # plot forces
    fig3, axs3 = plt.subplots(3,1)
    axs3[0].set_title('Ground reaction forces point 1')
    axs3[0].plot(t, l[0,:], linewidth=1.5)
    axs3[0].set_ylabel('Normal')
    axs3[1].plot(t, l[1,:] - l[3,:], linewidth=1.5)
    axs3[1].set_ylabel('Friction-x')
    axs3[2].plot(t, l[2, :] - l[4,:], linewidth=1.5)
    axs3[2].set_ylabel('Friction-y')
    # axs3[2].set_ylim(-0.5, 3)
    axs3[2].set_xlabel('Time (s)')

    fig4, axs4 = plt.subplots(3,1)
    axs4[0].set_title('Ground reaction forces point 2')
    axs4[0].plot(t, l[5,:], linewidth=1.5)
    axs4[0].set_ylabel('Normal')
    axs4[1].plot(t, l[6,:] - l[8,:], linewidth=1.5)
    axs4[1].set_ylabel('Friction-x')
    axs4[2].plot(t, l[7, :] - l[9,:], linewidth=1.5)
    axs4[2].set_ylabel('Friction-y')
    # axs4[2].set_ylim(-0.5, 3)
    axs4[2].set_xlabel('Time (s)')
    plt.show()