import numpy as np
import matplotlib.pyplot as plt

x = np.loadtxt('x.txt')
u = np.loadtxt('u.txt')
l = np.loadtxt('l.txt')
t = np.loadtxt('t.txt')

# fig3, axs3 = plt.subplots(3,1)
# axs3[0].plot(t, l[0,:], linewidth=1.5)
# axs3[0].set_ylabel('Normal')
# axs3[0].set_title('Ground reaction forces')
# axs3[1].plot(t, l[2,:] - l[6,:], linewidth=1.5)
# axs3[1].set_ylabel('Friction-x')

# axs3[2].plot(t, l[4, :] - l[8,:], linewidth=1.5)
# axs3[2].set_ylabel('Friction-y')
# # axs3[2].set_ylim(-0.5, 3)
# axs3[2].set_xlabel('Time (s)')

# fig4, axs4 = plt.subplots(3,1)
# axs4[0].set_title('Ground reaction forces point 2')
# axs4[0].plot(t, l[1,:], linewidth=1.5)
# axs4[0].set_ylabel('Normal')
# axs4[1].plot(t, l[3,:] - l[7,:], linewidth=1.5)
# axs4[1].set_ylabel('Friction-x')
# axs4[2].plot(t, l[5, :] - l[9,:], linewidth=1.5)
# axs4[2].set_ylabel('Friction-y')
fig3, axs3 = plt.subplots(3,1)
axs3[0].set_title('Ground reaction forces point 1')
axs3[0].plot(t, l[0,:], linewidth=1.5)
axs3[0].set_ylabel('Normal')
axs3[1].plot(t, l[2,:] - l[4,:], linewidth=1.5)
axs3[1].set_ylabel('Friction-x')
axs3[2].plot(t, l[2, :] - l[4,:], linewidth=1.5)
axs3[2].set_ylabel('Friction-y')
# axs3[2].set_ylim(-0.5, 3)
axs3[2].set_xlabel('Time (s)')

fig4, axs4 = plt.subplots(3,1)
axs4[0].set_title('Ground reaction forces point 2')
axs4[0].plot(t, l[1,:], linewidth=1.5)
axs4[0].set_ylabel('Normal')
axs4[1].plot(t, l[1,:] - l[8,:], linewidth=1.5)
axs4[1].set_ylabel('Friction-x')
axs4[2].plot(t, l[7, :] - l[9,:], linewidth=1.5)
axs4[2].set_ylabel('Friction-y')
# axs4[2].set_ylim(-0.5, 3)
axs4[2].set_xlabel('Time (s)')

fig5, axs5 = plt.subplots(2,1)
axs5[0].plot(t, l[2,:] - l[4,:] + l[6,:] - l[8,:], linewidth=1.5)
axs5[1].plot(t, l[3,:] - l[5,:] + l[7,:] - l[9,:], linewidth=1.5)
# Show the plots
plt.show()